/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyRankingRouteImport } from './routes/weekly-ranking'
import { Route as PlaylistsRouteImport } from './routes/playlists'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersUidRouteImport } from './routes/users.$uid'
import { Route as SongsSidRouteImport } from './routes/songs.$sid'
import { Route as PlaylistsPlstidRouteImport } from './routes/playlists.$plstid'
import { Route as ArtistArtistIdRouteImport } from './routes/artist.$artistId'

const WeeklyRankingRoute = WeeklyRankingRouteImport.update({
  id: '/weekly-ranking',
  path: '/weekly-ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRoute = PlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUidRoute = UsersUidRouteImport.update({
  id: '/users/$uid',
  path: '/users/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsSidRoute = SongsSidRouteImport.update({
  id: '/songs/$sid',
  path: '/songs/$sid',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsPlstidRoute = PlaylistsPlstidRouteImport.update({
  id: '/$plstid',
  path: '/$plstid',
  getParentRoute: () => PlaylistsRoute,
} as any)
const ArtistArtistIdRoute = ArtistArtistIdRouteImport.update({
  id: '/artist/$artistId',
  path: '/artist/$artistId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/playlists': typeof PlaylistsRouteWithChildren
  '/weekly-ranking': typeof WeeklyRankingRoute
  '/artist/$artistId': typeof ArtistArtistIdRoute
  '/playlists/$plstid': typeof PlaylistsPlstidRoute
  '/songs/$sid': typeof SongsSidRoute
  '/users/$uid': typeof UsersUidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/playlists': typeof PlaylistsRouteWithChildren
  '/weekly-ranking': typeof WeeklyRankingRoute
  '/artist/$artistId': typeof ArtistArtistIdRoute
  '/playlists/$plstid': typeof PlaylistsPlstidRoute
  '/songs/$sid': typeof SongsSidRoute
  '/users/$uid': typeof UsersUidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/playlists': typeof PlaylistsRouteWithChildren
  '/weekly-ranking': typeof WeeklyRankingRoute
  '/artist/$artistId': typeof ArtistArtistIdRoute
  '/playlists/$plstid': typeof PlaylistsPlstidRoute
  '/songs/$sid': typeof SongsSidRoute
  '/users/$uid': typeof UsersUidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/playlists'
    | '/weekly-ranking'
    | '/artist/$artistId'
    | '/playlists/$plstid'
    | '/songs/$sid'
    | '/users/$uid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/playlists'
    | '/weekly-ranking'
    | '/artist/$artistId'
    | '/playlists/$plstid'
    | '/songs/$sid'
    | '/users/$uid'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/playlists'
    | '/weekly-ranking'
    | '/artist/$artistId'
    | '/playlists/$plstid'
    | '/songs/$sid'
    | '/users/$uid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  PlaylistsRoute: typeof PlaylistsRouteWithChildren
  WeeklyRankingRoute: typeof WeeklyRankingRoute
  ArtistArtistIdRoute: typeof ArtistArtistIdRoute
  SongsSidRoute: typeof SongsSidRoute
  UsersUidRoute: typeof UsersUidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekly-ranking': {
      id: '/weekly-ranking'
      path: '/weekly-ranking'
      fullPath: '/weekly-ranking'
      preLoaderRoute: typeof WeeklyRankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$uid': {
      id: '/users/$uid'
      path: '/users/$uid'
      fullPath: '/users/$uid'
      preLoaderRoute: typeof UsersUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$sid': {
      id: '/songs/$sid'
      path: '/songs/$sid'
      fullPath: '/songs/$sid'
      preLoaderRoute: typeof SongsSidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$plstid': {
      id: '/playlists/$plstid'
      path: '/$plstid'
      fullPath: '/playlists/$plstid'
      preLoaderRoute: typeof PlaylistsPlstidRouteImport
      parentRoute: typeof PlaylistsRoute
    }
    '/artist/$artistId': {
      id: '/artist/$artistId'
      path: '/artist/$artistId'
      fullPath: '/artist/$artistId'
      preLoaderRoute: typeof ArtistArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlaylistsRouteChildren {
  PlaylistsPlstidRoute: typeof PlaylistsPlstidRoute
}

const PlaylistsRouteChildren: PlaylistsRouteChildren = {
  PlaylistsPlstidRoute: PlaylistsPlstidRoute,
}

const PlaylistsRouteWithChildren = PlaylistsRoute._addFileChildren(
  PlaylistsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  PlaylistsRoute: PlaylistsRouteWithChildren,
  WeeklyRankingRoute: WeeklyRankingRoute,
  ArtistArtistIdRoute: ArtistArtistIdRoute,
  SongsSidRoute: SongsSidRoute,
  UsersUidRoute: UsersUidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
